uint8 DEFAULT            =0
uint8 AUTO_MAN           =1
uint8 SWITCH_TELE_ASS    =2
uint8 CONFIRM            =3
uint8 CANCEL             =4 
uint8 RETURN_HOME        =5
uint8 FOCUS_CAM          =6
uint8 MENUE              =7
                         
uint8 CHANGE_NS          =8
uint8 CHANGE_VIEWER      =9
                         
uint8 FRONT_CAM          =11
uint8 BACK_CAM           =12
uint8 MANI_CAM           =13
uint8 FIX_CAM            =14

uint8 status


