/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.c
**     Project     : ohm_mc_KV31_V2_ClosedLoop
**     Processor   : MKV31F512VLH12
**     Component   : MKV31F512LH12_4SDK
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Datasheet   : KV31P100M120SF7RM, Rev. 1, March 24, 2014
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-10-19, 07:43, # CodeGen: 0
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         SystemInit            - void SystemInit(void);
**         SystemCoreClockUpdate - void SystemCoreClockUpdate(void);
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

/* {Default RTOS Adapter} No RTOS includes */
#include "Cpu.h"
#include "Events.h"


#ifdef __cplusplus
extern "C" {
#endif

/*
** ===================================================================
**     Method      :  Common_Init (component MKV31F512LH12_4SDK)
**     Description :
**         Initialization of registers for that there is no 
**         initialization component.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMMON_INIT
void Common_Init(void)
{
}

#endif /* CPU_COMMON_INIT */
/*
** ===================================================================
**     Method      :  Components_Init (component MKV31F512LH12_4SDK)
**     Description :
**         Initialization of components (with exception for Peripheral
**         Initialization Components which are initialized in 
**         Peripherals_Init() method).
**         For example, if automatic initialization feature 
**         is enabled in LDD component then its Init method call 
**         is executed in Components_Init() method.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMPONENTS_INIT
void Components_Init(void)
{

  /*! DAC_MOT2 Auto initialization start */
  DAC_DRV_Init(DAC_MOT2_IDX, &DAC_MOT2_InitConfig0);
  DAC_DRV_ConfigBuffer(DAC_MOT2_IDX, &MOT2_SETVALUESPEED_3V3);
  /*! DAC_MOT2 Auto initialization end */
  
  /*! DAC_MOT1 Auto initialization start */
  DAC_DRV_Init(DAC_MOT1_IDX, &DAC_MOT1_InitConfig0);
  DAC_DRV_ConfigBuffer(DAC_MOT1_IDX, &DAC_MOT1_BufferInitConfig0);
  /*! DAC_MOT1 Auto initialization end */
  
  /*! MOT_EN Auto initialization start */
  GPIO_DRV_Init(NULL,MOT_EN_OutConfig0);
  /*! MOT_EN Auto initialization end */
  
  /*! MOT_RDY Auto initialization start */
  GPIO_DRV_Init(MOT_RDY_InpConfig0,NULL);
  /*! MOT_RDY Auto initialization end */
  
  /*! MOT_DIR Auto initialization start */
  GPIO_DRV_Init(NULL,MOT_DIR_OutConfig0);
  /*! MOT_DIR Auto initialization end */
  
  /*! MOT1_QD Auto initialization start */
  FTM_DRV_Init(MOT1_QD_IDX,&MOT1_QD_InitConfig0);
  FTM_DRV_SetClock(MOT1_QD_IDX, kClock_source_FTM_SystemClk, kFtmDividedBy1);
  FTM_DRV_QuadDecodeStart(MOT1_QD_IDX, &MOT1_QD_ENC, &MOT1_QD_ENC, kFtmQuadPhaseEncode);
  FTM_DRV_SetTimeOverflowIntCmd(MOT1_QD_IDX,false);
  FTM_DRV_SetFaultIntCmd(MOT1_QD_IDX,false);
  /*! MOT1_QD Auto initialization end */
  
  /*! MOT2_QD Auto initialization start */
  FTM_DRV_Init(MOT2_QD_IDX,&MOT2_QD_InitConfig0);
  FTM_DRV_SetClock(MOT2_QD_IDX, kClock_source_FTM_SystemClk, kFtmDividedBy1);
  FTM_DRV_QuadDecodeStart(MOT2_QD_IDX, &MOT2_QD_QdConfig0, &MOT2_QD_QdConfig0, kFtmQuadPhaseEncode);
  FTM_DRV_SetTimeOverflowIntCmd(MOT2_QD_IDX,false);
  FTM_DRV_SetFaultIntCmd(MOT2_QD_IDX,false);
  /*! MOT2_QD Auto initialization end */
  
  /*! MOT1_LED Auto initialization start */
  GPIO_DRV_Init(NULL,MOT1_LED_OutConfig0);
  /*! MOT1_LED Auto initialization end */
  
  /*! MOT2_LED Auto initialization start */
  GPIO_DRV_Init(NULL,MOT2_LED_OutConfig0);
  /*! MOT2_LED Auto initialization end */
  
  /*! BRD_SEL Auto initialization start */
  GPIO_DRV_Init(BRD_SEL_InpConfig0,NULL);
  /*! BRD_SEL Auto initialization end */
  
  /*! REF_INT Auto initialization start */
  GPIO_DRV_Init(REF_INT_InpConfig0,NULL);
  /*! REF_INT Auto initialization end */
  
  /*! MOT_ADC Auto initialization start */
  ADC16_DRV_Init(MOT_ADC_IDX, &MOT1_AN);
  ADC16_DRV_ConfigConvChn(MOT_ADC_IDX, 0U, &MOT_ADC_ChnConfig0);
  /*! MOT_ADC Auto initialization end */

  /*! QD_SEL Auto initialization start */
  GPIO_DRV_Init(NULL,QD_SEL_OutConfig0);
  /*! QD_SEL Auto initialization end */
  
  /*! dmaController1 Auto initialization start */
  EDMA_DRV_Init(&dmaController1_State,&dmaController1_InitConfig0);
  /*! dmaController1 Auto initialization end */
  
  /*! dspiCom1 Auto initialization start */
  NVIC_SetPriority(SPI0_IRQn, 7U);
  OSA_InstallIntHandler(SPI0_IRQn, dspiCom1_IRQHandler);
  DSPI_DRV_EdmaSlaveInit(dspiCom1_IDX, &dspiCom1_SlaveState, &dspiCom1_SlaveConfig0);
  /*! dspiCom1 Auto initialization end */
  
  /*! pitTimer1 Auto initialization start */
  NVIC_SetPriority(PIT0_IRQn, 0U);
  OSA_InstallIntHandler(PIT0_IRQn,  pitTimer1_IRQHandler);
  PIT_DRV_Init(pitTimer1_IDX,true);
  PIT_DRV_InitChannel(pitTimer1_IDX,pitTimer1_CHANNEL,&pitTimer1_InitConfig0);
  PIT_DRV_StartTimer(pitTimer1_IDX,pitTimer1_CHANNEL);
  /*! pitTimer1 Auto initialization end */
}
#endif /* CPU_COMPONENTS_INIT */


#ifdef __cplusplus
}
#endif

/* END Cpu. */

